package simple.guard.api.error.domain;

public enum SimpleGuardErrorCode {
    INVALID_TOKEN,
    ACCESS_DENIED,
    CRITICAL_ACTION_CONFIRMATION_REQUIRED,
    DEVICE_NOT_FOUND,
    DEVICE_ALREADY_PAIRED,
    PAIRING_SESSION_EXPIRED,
    PAIRING_SESSION_ALREADY_USED,
    VALIDATION_ERROR,
    MAX_OPEN_PAIRING_SESSIONS_REACHED,
    INTERNAL_ERROR
}
